spring.application.name=iot-api

# Configuraciones postgres
#spring.datasource.url=jdbc:postgresql://iot-databaseinstance-21wlewiz8brb.cfoc4ccq2avl.us-east-1.rds.amazonaws.com:5432/iotdb
#spring.datasource.username=dbuser
#spring.datasource.password=PostgreSQL2025
spring.datasource.url=jdbc:postgresql://localhost:5432/iotdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

camel.springboot.main-run-controller = true
# camel-activemq config
camel.component.activemq.broker-url=tcp://186.64.120.248:61617
camel.component.activemq.username=admin
camel.component.activemq.password=admin
camel.component.activemq.use-pooled-connection=true
camel.component.activemq.use-single-connection=false
camel.component.activemq.cache-level-name=CACHE_CONSUMER
camel.component.activemq.transacted=true

# SSL Config
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=talento
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=https-iot-cert

